 firehose:
    doppler-url: ws://doppler.10.1.1.11.xip.io
    doppler-events: "ValueMetric,CounterEvent,ContainerMetric"
    output-json: true
    #only needed if you are deploying to CF
    authentication-url:
    cf-domain:
    username:
    password:
    trust-self-certs: true

 security:
    user:
       password: s3cr3t


 logging:
     level:
        org.springframework.cloud: DEBUG